# Generated by Django 3.2.9 on 2021-12-10 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UOM', models.CharField(default='kg', max_length=10, verbose_name='Unit Of Measurement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='all_trainee_measurements', to='trainees.trainee')),
            ],
        ),
    ]
