# Generated by Django 3.2.9 on 2021-12-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0002_weightmeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightmeasurement',
            name='user_input_date',
            field=models.DateField(null=True, verbose_name='User Measurement Date'),
        ),
    ]
