# Generated by Django 3.2.9 on 2021-12-11 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
        ('trainees', '0004_alter_weightmeasurement_user_input_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='all_trainees', to='trainers.trainer'),
        ),
    ]
